
// ignore_for_file: constant_identifier_names

enum Constant {

  OPTION_BOX_SIZE(64),
  OPTION_BOX_PADDING(8),
  OPTION_ROW_COUNT(3),
  OPTION_BOX_WIDTH(160),
  OPTION_BOX_HEIGHT(56),
  OPTION_FILL_TRANS_DURATION(300),

  BORDER_RADIUS(8),
  BORDER_WIDTH(1.6),

  SIDETAB_WIDTH(136),
  SIDETAB_BUTTON_A(48),
  SIDETAB_BUTTON_r(24),
  SIDETAB_BUTTON_R(24),
  SIDETAB_OFFSET(8),
  SIDETAB_TRANS_DURATION(200),

  FILL_BOX_TRANS_DURATION(400)
  ;

  final double value;
  const Constant(this.value);
}