
// ignore_for_file: constant_identifier_names

enum Constant {

  PADDING(16),

  SIDETAB_BUTTON_HEIGHT(40),

  SPLASH_CLOVER_R(16),
  SPLASH_CLOVER_SPACE(4),
  SPLASH_CLOVER_DURATION(700),
  SPLASH_CLOVER_WAIT(0),
  SPALSH_CLOVER_ARC(90),
  SPALSH_CLOVER_ANIMATION(6),

  RESULT_BUTTON_HEGHT(56),
  RESULT_RADIUS(96),
  RESULT_COL_WIDTH(156),
  RESULT_COL_LEFT_PADDING(48),

  OPTION_ICON_SIZE(24),
  OPTION_BOX_DIAMETER(48),
  OPTION_BOX_PADDING(8),
  OPTION_COL_COUNT(4),
  OPTION_DOT_HEIGHT(12),
  OPTION_DOT_WIDTH(4),
  OPTION_BOX_WIDTH(88),
  OPTION_BOX_HEIGHT(104),
  OPTION_FILL_TRANS_DURATION(300),

  BORDER_RADIUS(8),
  BORDER_WIDTH(1.6),

  SIDETAB_WIDTH(136),
  SIDETAB_BUTTON_A(48),
  SIDETAB_BUTTON_r(24),
  SIDETAB_BUTTON_R(24),
  SIDETAB_OFFSET(8),
  SIDETAB_TRANS_DURATION(200),

  FILL_BOX_TRANS_DURATION(400)
  ;

  final double value;
  const Constant(this.value);
}