name: chicken
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  http: ^0.13.4
  scrollable_positioned_list: ^0.3.2
  shared_preferences: ^2.0.15
  test: ^1.21.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
# flutter_launcher_icons:
#   git:
#     url: https://github.com/Davenchy/flutter_launcher_icons.git
#     ref: fixMinSdkParseFlutter2.8
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
